apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: api
spec:
  provider: azure                             
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: SQL_DBNAME                           # data field to populate
      objectName: SQL-DBNAME                        # name of the mounted content to sync. this could be the object name or the object alias
    - key: SQL_PASSWORD                           # data field to populate
      objectName: SQL-PASSWORD                        # name of the mounted content to sync. this could be the object name or the object alias
    - key: SQL_SERVER                         # data field to populate
      objectName: SQL-SERVER                        # name of the mounted content to sync. this could be the object name or the object alias
    - key: SQL_USER                           # data field to populate
      objectName: SQL-USER                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: foosecret                     # name of the Kubernetes Secret object
    type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls