kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webdev-webrolebinding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webdev-webrole
subjects:
- kind: Group
  namespace: web
  name: 0b49092a-5c6a-4701-a31c-255ca6e383bb